# Getting Error while exporting the dataset in MySQL Workbench

**User**: carlton
**URL**: [https://discourse.onlinedegree.iitm.ac.in/t/getting-error-while-exporting-the-dataset-in-mysql-workbench/137940/2](https://discourse.onlinedegree.iitm.ac.in/t/getting-error-while-exporting-the-dataset-in-mysql-workbench/137940/2)

Hi Pratik,

Instead of trying to use the MySQL Workbench, its easier to connect to the database using the sqlalchemy with parameters given in this notebook that was provided in the portal.

![](https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/6/0/60ea89b7f54e26db2606ac3e2bd08e106605d5ec.png)
[colab.research.google.com](https://colab.research.google.com/drive/1j_5AsWdf0SwVHVgfbEAcg7vYguKUN41o)

![](https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/5/b/5b77e9737d5f8f8bc5f7b35e7fc0f8088fd1ebd8.png)

### [Google Colab](https://colab.research.google.com/drive/1j_5AsWdf0SwVHVgfbEAcg7vYguKUN41o)

[![Screenshot 2024-07-04 at 19.22.57](https://europe1.discourse-cdn.com/flex013/uploads/iitm/optimized/3X/e/6/e68540171b607902533a6cb4153410b35c1484f9_2_690x272.png)

Screenshot 2024-07-04 at 19.22.572452Ã—970 415 KB](https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/e/6/e68540171b607902533a6cb4153410b35c1484f9.png "Screenshot 2024-07-04 at 19.22.57")

Kind regards
